[tool.poetry]
name = "pythonproject7"
version = "0.1.0"
description = ""
authors = ["Olga <solevla2016@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.dev.dependencies]
black = "^26.3.1"
flake8 = "^7.3.0"
isort = "^8.0.1"
mypy = "^1.19.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
